### ISSUE TITLE
build.sh error 

### ISSUE THREAD

**Issue by edgar-explorer** [slightech/MYNT-EYE-ORB-SLAM2-Sample#1]
[ 73%] Building CXX object CMakeFiles/rgbd_tum.dir/Examples/RGB-D/rgbd_tum.cc.o
[ 76%] Building CXX object CMakeFiles/stereo_mynteye.dir/Examples/Stereo/stereo_mynteye.cc.o
[ 79%] Building CXX object CMakeFiles/mono_kitti.dir/Examples/Monocular/mono_kitti.cc.o
/home/cc/catkin_ws/src/MYNT-EYE-ORB-SLAM2-Sample-mynteye/Examples/Stereo/stereo_mynteye.cc:33:20: fatal error: camera.h: No such file or directory
compilation terminated.
CMakeFiles/stereo_mynteye.dir/build.make:62: recipe for target 'CMakeFiles/stereo_mynteye.dir/Examples/Stereo/stereo_mynteye.cc.o' failed
make[2]: *** [CMakeFiles/stereo_mynteye.dir/Examples/Stereo/stereo_mynteye.cc.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/stereo_mynteye.dir/all' failed
make[1]: *** [CMakeFiles/stereo_mynteye.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 82%] Linking CXX executable ../Examples/Stereo/stereo_kitti
[ 85%] Linking CXX executable ../Examples/Stereo/stereo_euroc
[ 88%] Linking CXX executable ../Examples/Monocular/mono_tum
[ 88%] Built target stereo_kitti
[ 88%] Built target stereo_euroc
[ 88%] Built target mono_tum
[ 91%] Linking CXX executable ../Examples/Monocular/mono_euroc
[ 94%] Linking CXX executable ../Examples/RGB-D/rgbd_tum
[ 97%] Linking CXX executable ../Examples/Monocular/mono_kitti
[ 97%] Built target mono_euroc
[ 97%] Built target mono_kitti
[ 97%] Built target rgbd_tum
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by derekhe89** [comment]
hello, you can print the env of MYNTEYE_ROOT to make sure if MYNTEYE SDK installed sucessed.

**Comment by Quitino** [comment]
编译的时候出现错误如下：
/MYNT-EYE-ORB-SLAM2/Examples/Stereo/stereo_mynt.cc:28:28: fatal error: mynteye/logger.h: 没有那个文件或目录
怎么解决啊这个？？

**Comment by edgar-explorer** [comment]
@boonvon  you did not install MYNTEYE SDK installed sucessed and try again
