### ISSUE TITLE
摄像头尺度与实际尺度相差较大

### ISSUE THREAD

**Issue by Junhuan-Peng** [slightech/MYNT-EYE-ORB-SLAM2-Sample#3]
程序运行时，对自己的位置估计偏差较大，尺度比实际情况小很多，而且在水平移动的时候，会认为自己有一个旋转。请问怎样能解决这个问题呢？

**Comment by jiziye** [comment]
请问跑的是单目还是双目？

**Comment by yiran1012** [comment]
跟我碰到的问题完全一致，请问解决了吗

**Comment by Junhuan-Peng** [comment]
不好意思，当时的项目因为一些原因已经终止了。这个问题后面我们也没有深入研究解决。
