### ISSUE TITLE
glog_init.h: No such file or directory

### ISSUE THREAD

**Issue by 510443664** [slightech/MYNT-EYE-ORB-SLAM2-Sample#6]
When building, came across this problem.
[ 70%] Building CXX object CMakeFiles/stereo_mynt.dir/Examples/Stereo/stereo_mynt.cc.o
/home/lyh/MYNT-EYE-ORB-SLAM2-Sample-sdk2/Examples/Stereo/stereo_mynt.cc:28:31: fatal error: mynteye/glog_init.h: No such file or directory
compilation terminated.

**Comment by myton** [comment]
Hello, this problem has been fixed.
