### ISSUE TITLE
How to adjust parameters in yaml file?

### ISSUE THREAD

**Issue by huchhong** [slightech/MYNT-EYE-ORB-SLAM2-Sample#8]
I have some questions about the config file mynteye_s_stereo.yaml. 

First, the distortion parameters are all set to zero, does that means images from sdk would be already well calibrated ? we only need to fill Camera.fx, Camera.fy, etc, parameters from LEFT.P and RIGHT.P ?

Second, why Camera.bf is set to 80, this is very different from Camera.fx times baseline (12cm). 

Last, does rectification parameters need to be set? As far as i see from source code, these params are never used.

**Comment by harjeb** [comment]
ORB直接订阅的相机矫正图 不需要用矫正参数, 配置中的bf值：bf只是比例的缩放，不影响轨迹本身。这里的80主要是为了多个相机统一使用一份配置，也可自行修改为所使用的相机的bf值。
